### ISSUE TITLE
CSS `!important` 

### ISSUE THREAD

**Issue by ozntel** [nyable/obsidian-code-block-enhancer#2]
Thanks for the plugin. I was planning to do something like that but didn't have much time :-)
Would be an issue if you remove `!important!` rules from your CSS code? I can not overwrite them with custom snippets (Especially the one with padding)
Thanks!

**Comment by nyable** [comment]
Thanks for the feedback.I'm trying to replace ‘!important’, and some modifications have been made in the new version
But if I want to align line numbers under different themes, I have to use some`!important` to ensure that the `font-size` and `line-height` are consistent.

**Comment by ozntel** [comment]
Sure, thanks! Removing `important` flag from `padding-left` works for me just fine! :-)
